const state={scenarios:[],filter:"",currentBg:"./assets/backgrounds/room.svg",leftChar:"./assets/characters/male_casual.svg",rightChar:"./assets/characters/female_casual.svg",currentScenario:null,actIndex:0,stepIndex:0};
async function loadScenarios(){const r=await fetch("./data/scenarios.json",{cache:"no-store"});const d=await r.json();state.scenarios=d.scenarios;document.querySelector("#version").textContent=d.version;renderList();}
function renderList(){const list=document.querySelector(".list");list.innerHTML="";state.scenarios.forEach(s=>{const el=document.createElement("div");el.textContent=`${s.title} (Acts: ${s.acts.length})`;el.className="item";el.onclick=()=>selectScenario(s);list.appendChild(el);});}
function selectScenario(s){state.currentScenario=s;state.actIndex=0;state.stepIndex=0;document.querySelector("#sceneTitle").textContent=s.title;document.querySelector(".bg").style.backgroundImage=`url('${state.currentBg}')`;document.querySelector("#left img").src=state.leftChar;document.querySelector("#right img").src=state.rightChar;updateActUI();renderStep();}
function updateActUI(){const s=state.currentScenario;const a=s.acts[state.actIndex];document.querySelector("#actBadge").textContent=`Act ${state.actIndex+1}/${s.acts.length}`;document.querySelector("#actTitle").textContent=a.title;}
function renderStep(){const s=state.currentScenario;const a=s.acts[state.actIndex];const t=a.steps[state.stepIndex];document.querySelector("#dialog").textContent=t;const last=state.stepIndex>=a.steps.length-1;document.querySelector("#nextBtn").textContent=last?(state.actIndex<s.acts.length-1?"Next Act":"Finish"):"Next";document.querySelector("#prevBtn").disabled=(state.stepIndex===0&&state.actIndex===0);}
function next(){const s=state.currentScenario;const a=s.acts[state.actIndex];if(state.stepIndex<a.steps.length-1){state.stepIndex++;}else if(state.actIndex<s.acts.length-1){state.actIndex++;state.stepIndex=0;updateActUI();}else{document.querySelector("#dialog").textContent="🎉 Scenario complete!";document.querySelector("#nextBtn").disabled=true;}renderStep();}
function prev(){const s=state.currentScenario;if(!s)return;if(state.stepIndex>0){state.stepIndex--;}else if(state.actIndex>0){state.actIndex--;const a=s.acts[state.actIndex];state.stepIndex=a.steps.length-1;updateActUI();}renderStep();}
function bindUI(){document.querySelector("#search").addEventListener("input",e=>{renderList();});document.querySelector("#bgSelect").addEventListener("change",e=>{document.querySelector(".bg").style.backgroundImage=`url('${e.target.value}')`;});document.querySelector("#leftSelect").addEventListener("change",e=>{document.querySelector("#left img").src=e.target.value;});document.querySelector("#rightSelect").addEventListener("change",e=>{document.querySelector("#right img").src=e.target.value;});document.querySelector("#nextBtn").addEventListener("click",next);document.querySelector("#prevBtn").addEventListener("click",prev);}
window.addEventListener("DOMContentLoaded",async()=>{bindUI();await loadScenarios();});