name: Lighthouse

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: '0 3 * * *'  # nightly at 03:00 UTC

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Lighthouse (desktop) on production with ?nosw=1
        run: bash tools/run-lighthouse.sh
        env:
          SITE_URL: https://amorvia.eu

      - name: Upload Lighthouse report
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: lighthouse/*
