name: lighthouse

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Resolve target URL
        id: url
        run: |
          if [ -n "${{ secrets.LIGHTHOUSE_URL }}" ]; then
            echo "url=${{ secrets.LIGHTHOUSE_URL }}" >> $GITHUB_OUTPUT
          else
            echo "url=https://www.amorvia.eu/" >> $GITHUB_OUTPUT
          fi
          echo "Target URL: ${{ steps.url.outputs.url }}"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Lighthouse CI
        run: npm i -g @lhci/cli

      - name: Run Lighthouse
        run: |
          lhci autorun             --collect.url=${{ steps.url.outputs.url }}             --upload.target=filesystem             --assert.assertions.'categories:performance'=error@90             --assert.assertions.'categories:accessibility'=error@90             --assert.assertions.'categories:seo'=error@90             --assert.assertions.'categories:best-practices'=error@90

      - name: Upload LHCI reports
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: .lighthouseci/**
